# Generated by Django 5.2.5 on 2025-10-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
